/**
 * Standardized error codes for the application
 * These codes are used by ApiError and in error responses
 */
export enum ErrorCode {
  // Authentication
  NOT_AUTHENTICATED = 'NOT_AUTHENTICATED',
  INVALID_CREDENTIALS = 'INVALID_CREDENTIALS',
  FORBIDDEN = 'FORBIDDEN',
  TOKEN_EXPIRED = 'TOKEN_EXPIRED',
  INVALID_TOKEN = 'INVALID_TOKEN',
  
  // Resource errors
  RESOURCE_NOT_FOUND = 'RESOURCE_NOT_FOUND',
  USER_NOT_FOUND = 'USER_NOT_FOUND',
  EVENT_NOT_FOUND = 'EVENT_NOT_FOUND',
  BOOKING_NOT_FOUND = 'BOOKING_NOT_FOUND',
  TICKET_NOT_FOUND = 'TICKET_NOT_FOUND',
  SEAT_NOT_FOUND = 'SEAT_NOT_FOUND',
  
  // Validation errors
  VALIDATION_ERROR = 'VALIDATION_ERROR',
  MISSING_REQUIRED_FIELDS = 'MISSING_REQUIRED_FIELDS',
  INVALID_INPUT = 'INVALID_INPUT',
  
  // Business logic errors
  SEATS_UNAVAILABLE = 'SEATS_UNAVAILABLE',
  BOOKING_ALREADY_CANCELLED = 'BOOKING_ALREADY_CANCELLED',
  CANNOT_CANCEL_BOOKING = 'CANNOT_CANCEL_BOOKING',
  DUPLICATE_RESOURCE = 'DUPLICATE_RESOURCE',
  EMAIL_ALREADY_EXISTS = 'EMAIL_ALREADY_EXISTS',
  EVENT_FULL = 'EVENT_FULL',
  PAYMENT_FAILED = 'PAYMENT_FAILED',
  INVALID_PAYMENT = 'INVALID_PAYMENT',
  SESSION_EXPIRED = 'SESSION_EXPIRED',
  
  // System errors
  INTERNAL_ERROR = 'INTERNAL_ERROR',
  DATABASE_ERROR = 'DATABASE_ERROR',
  EXTERNAL_SERVICE_ERROR = 'EXTERNAL_SERVICE_ERROR',
  RATE_LIMIT_EXCEEDED = 'RATE_LIMIT_EXCEEDED',
} 