name: Frontend Tests

on:
  push:
    branches: [ main, develop ]
    paths:
      - 'eventia-ticketing-flow1/**'
  pull_request:
    branches: [ main, develop ]
    paths:
      - 'eventia-ticketing-flow1/**'

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: './eventia-ticketing-flow1/package-lock.json'
      
      - name: Install dependencies
        working-directory: ./eventia-ticketing-flow1
        run: npm ci
      
      - name: Run unit tests
        working-directory: ./eventia-ticketing-flow1
        run: npm run test:unit
      
      - name: Upload test coverage
        uses: actions/upload-artifact@v3
        with:
          name: frontend-unit-coverage
          path: ./eventia-ticketing-flow1/coverage
      
      - name: Report coverage
        uses: codecov/codecov-action@v3
        with:
          directory: ./eventia-ticketing-flow1/coverage
          flags: frontend-unit-tests

  e2e-tests:
    runs-on: ubuntu-latest
    needs: unit-tests
    
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: './eventia-ticketing-flow1/package-lock.json'
      
      - name: Install dependencies
        working-directory: ./eventia-ticketing-flow1
        run: npm ci
      
      - name: Install Playwright
        working-directory: ./eventia-ticketing-flow1
        run: npx playwright install --with-deps chromium
      
      - name: Start backend mock (if needed)
        run: |
          npm install -g json-server
          json-server --watch ./eventia-ticketing-flow1/src/__tests__/mocks/api-data.json --port 3001 &
      
      - name: Build and start frontend
        working-directory: ./eventia-ticketing-flow1
        run: |
          npm run build
          npm run preview -- --port 5173 &
      
      - name: Wait for frontend to start
        run: sleep 5
      
      - name: Run E2E tests
        working-directory: ./eventia-ticketing-flow1
        run: npm run test:e2e
        env:
          BASE_URL: http://localhost:5173
      
      - name: Upload test artifacts
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: playwright-report
          path: ./eventia-ticketing-flow1/playwright-report 